spring.application.name=linksphere

#server.port=${PORT:8080}
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/linksphere
#spring.datasource.username=postgres
#spring.datasource.password=qwertyuiop
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.url=${linksphere_db_ty2m}
spring.datasource.username=${linksphere_db_ty2m_user}
spring.datasource.password=${gNnmyu9QnMQQJDnGQRFN6pXnOWt9IFZs}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
