spring.application.name=linksphere

#Server
server.port=8080

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/linksphere
spring.datasource.username=postgres
spring.datasource.password=qwertyuiop
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform = org.hibernate.dialect.PostgresPlusDialect

